services:
  web:
    build: 
      context: .. #portfolio
      args: #variables en dockerfile para la construcci√≥n de la
        - USUARIO=maria
      dockerfile: ./deploy/Dockerfile
    container_name: ctportfolio
    env_file:
      - ./.env
    volumes:
      - ./logs:/root/logs
    networks:
      - netcaronte:
        ipv4_address: $(IP)
networks:
  netcaronte:
    ipam:
      driver: default
      config:
        - subnet: $(SUBNET) 